// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0S-6smQTLNDLRdIGBvLtv2ZAo8dKHezo',
    appId: '1:89314856398:android:155fad8b6665dd7257af9f',
    messagingSenderId: '89314856398',
    projectId: 'adtest-76f2f',
    storageBucket: 'adtest-76f2f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BX-tBZi6cSgNMrnh3M8vlzHJar-Ql8M',
    appId: '1:89314856398:web:42f0eee108d12f9757af9f',
    messagingSenderId: '89314856398',
    projectId: 'adtest-76f2f',
    authDomain: 'adtest-76f2f.firebaseapp.com',
    storageBucket: 'adtest-76f2f.firebasestorage.app',
    measurementId: 'G-0T2XQWLC2Z',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvEf-lENbCJ33IQBLsYVDXF1D_dMPIor8',
    appId: '1:89314856398:ios:d4124822986dd4b557af9f',
    messagingSenderId: '89314856398',
    projectId: 'adtest-76f2f',
    storageBucket: 'adtest-76f2f.firebasestorage.app',
    iosBundleId: 'com.yencodetech.vpn',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvEf-lENbCJ33IQBLsYVDXF1D_dMPIor8',
    appId: '1:89314856398:ios:d4124822986dd4b557af9f',
    messagingSenderId: '89314856398',
    projectId: 'adtest-76f2f',
    storageBucket: 'adtest-76f2f.firebasestorage.app',
    iosBundleId: 'com.yencodetech.vpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-BX-tBZi6cSgNMrnh3M8vlzHJar-Ql8M',
    appId: '1:89314856398:web:62efb4ae646f1d6757af9f',
    messagingSenderId: '89314856398',
    projectId: 'adtest-76f2f',
    authDomain: 'adtest-76f2f.firebaseapp.com',
    storageBucket: 'adtest-76f2f.firebasestorage.app',
    measurementId: 'G-N3Q12BTY74',
  );

}